/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_TRANSIT_REALTIME_COM_GOOGLE_TRANSIT_REALTIME_GTFS_REALTIME_NYCT_PB_H_INCLUDED
#define PB_TRANSIT_REALTIME_COM_GOOGLE_TRANSIT_REALTIME_GTFS_REALTIME_NYCT_PB_H_INCLUDED
#include <pb.h>
#include "com/google/transit/realtime/gtfs-realtime.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* The direction the train is moving. */
typedef enum _transit_realtime_NyctTripDescriptor_Direction {
    transit_realtime_NyctTripDescriptor_Direction_NORTH = 1,
    transit_realtime_NyctTripDescriptor_Direction_EAST = 2,
    transit_realtime_NyctTripDescriptor_Direction_SOUTH = 3,
    transit_realtime_NyctTripDescriptor_Direction_WEST = 4
} transit_realtime_NyctTripDescriptor_Direction;

/* Struct definitions */
typedef struct _transit_realtime_TripReplacementPeriod {
    /* The replacement period is for this route */
    pb_callback_t route_id;
    /* The start time is omitted, the end time is currently now + 30 minutes for
 all routes of the A division */
    bool has_replacement_period;
    transit_realtime_TimeRange replacement_period;
} transit_realtime_TripReplacementPeriod;

/* NYCT Subway extensions for the feed header */
typedef struct _transit_realtime_NyctFeedHeader {
    /* Version of the NYCT Subway extensions
 The current version is 1.0 */
    pb_callback_t nyct_subway_version;
    /* For the NYCT Subway, the GTFS-realtime feed replaces any scheduled
 trip within the trip_replacement_period. 
 This feed is a full dataset, it contains all trips starting 
 in the trip_replacement_period. If a trip from the static GTFS is not
 found in the GTFS-realtime feed, it should be considered as cancelled.
 The replacement period can be different for each route, so here is 
 a list of the routes where the trips in the feed replace all 
 scheduled trips within the replacement period. */
    pb_callback_t trip_replacement_period;
} transit_realtime_NyctFeedHeader;

/* NYCT Subway extensions for the trip descriptor */
typedef struct _transit_realtime_NyctTripDescriptor {
    /* The nyct_train_id is meant for internal use only. It provides an
 easy way to associated GTFS-realtime trip identifiers with NYCT rail
 operations identifier 
 
 The ATS office system assigns unique train identification (Train ID) to
 each train operating within or ready to enter the mainline of the
 monitored territory. An example of this is 06 0123+ PEL/BBR and is decoded
 as follows: 
 
 The first character represents the trip type designator. 0 identifies a
 scheduled revenue trip. Other revenue trip values that are a result of a
 change to the base schedule include; [= reroute], [/ skip stop], [$ turn
 train] also known as shortly lined service.  
 
 The second character 6 represents the trip line i.e. number 6 train The
 third set of characters identify the decoded origin time. The last
 character may be blank "on the whole minute" or + "30 seconds" 
 
 Note: Origin times will not change when there is a trip type change.  This
 is followed by a three character "Origin Location" / "Destination
 Location" */
    pb_callback_t train_id;
    /* This trip has been assigned to a physical train. If true, this trip is
 already underway or most likely will depart shortly. 

 Train Assignment is a function of the Automatic Train Supervision (ATS)
 office system used by NYCT Rail Operations to monitor and track train
 movements. ATS provides the ability to "assign" the nyct_train_id
 attribute when a physical train is at its origin terminal. These assigned
 trips have the is_assigned field set in the TripDescriptor.

 When a train is at a terminal but has not been given a work program it is
 declared unassigned and is tagged as such. Unassigned trains can be moved
 to a storage location or assigned a nyct_train_id when a determination for
 service is made. */
    bool has_is_assigned;
    bool is_assigned;
    /* Uptown and Bronx-bound trains are moving NORTH.
 Times Square Shuttle to Grand Central is also northbound.

 Downtown and Brooklyn-bound trains are moving SOUTH.
 Times Square Shuttle to Times Square is also southbound.
 
 EAST and WEST are not used currently. */
    bool has_direction;
    transit_realtime_NyctTripDescriptor_Direction direction;
} transit_realtime_NyctTripDescriptor;

/* NYCT Subway extensions for the stop time update */
typedef struct _transit_realtime_NyctStopTimeUpdate {
    /* Provides the planned station arrival track. The following is the Manhattan
 track configurations:
 1: southbound local
 2: southbound express
 3: northbound express
 4: northbound local

 In the Bronx (except Dyre Ave line)
 M: bi-directional express (in the AM express to Manhattan, in the PM
 express away).

 The Dyre Ave line is configured:
 1: southbound
 2: northbound
 3: bi-directional */
    pb_callback_t scheduled_track;
    /* This is the actual track that the train is operating on and can be used to
 determine if a train is operating according to its current schedule
 (plan).
 
 The actual track is known only shortly before the train reaches a station,
 typically not before it leaves the previous station. Therefore, the NYCT
 feed sets this field only for the first station of the remaining trip.
 
 Different actual and scheduled track is the result of manually rerouting a
 train off it scheduled path.  When this occurs, prediction data may become
 unreliable since the train is no longer operating in accordance to its
 schedule.  The rules engine for the 'countdown' clocks will remove this
 train from all schedule stations. */
    pb_callback_t actual_track;
} transit_realtime_NyctStopTimeUpdate;


/* Extensions */
extern const pb_extension_type_t transit_realtime_nyct_feed_header; /* field type: transit_realtime_NyctFeedHeader nyct_feed_header; */
extern const pb_extension_type_t transit_realtime_nyct_trip_descriptor; /* field type: transit_realtime_NyctTripDescriptor nyct_trip_descriptor; */
extern const pb_extension_type_t transit_realtime_nyct_stop_time_update; /* field type: transit_realtime_NyctStopTimeUpdate nyct_stop_time_update; */

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _transit_realtime_NyctTripDescriptor_Direction_MIN transit_realtime_NyctTripDescriptor_Direction_NORTH
#define _transit_realtime_NyctTripDescriptor_Direction_MAX transit_realtime_NyctTripDescriptor_Direction_WEST
#define _transit_realtime_NyctTripDescriptor_Direction_ARRAYSIZE ((transit_realtime_NyctTripDescriptor_Direction)(transit_realtime_NyctTripDescriptor_Direction_WEST+1))



#define transit_realtime_NyctTripDescriptor_direction_ENUMTYPE transit_realtime_NyctTripDescriptor_Direction



/* Initializer values for message structs */
#define transit_realtime_TripReplacementPeriod_init_default {{{NULL}, NULL}, false, transit_realtime_TimeRange_init_default}
#define transit_realtime_NyctFeedHeader_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define transit_realtime_NyctTripDescriptor_init_default {{{NULL}, NULL}, false, 0, false, _transit_realtime_NyctTripDescriptor_Direction_MIN}
#define transit_realtime_NyctStopTimeUpdate_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define transit_realtime_TripReplacementPeriod_init_zero {{{NULL}, NULL}, false, transit_realtime_TimeRange_init_zero}
#define transit_realtime_NyctFeedHeader_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define transit_realtime_NyctTripDescriptor_init_zero {{{NULL}, NULL}, false, 0, false, _transit_realtime_NyctTripDescriptor_Direction_MIN}
#define transit_realtime_NyctStopTimeUpdate_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define transit_realtime_TripReplacementPeriod_route_id_tag 1
#define transit_realtime_TripReplacementPeriod_replacement_period_tag 2
#define transit_realtime_NyctFeedHeader_nyct_subway_version_tag 1
#define transit_realtime_NyctFeedHeader_trip_replacement_period_tag 2
#define transit_realtime_NyctTripDescriptor_train_id_tag 1
#define transit_realtime_NyctTripDescriptor_is_assigned_tag 2
#define transit_realtime_NyctTripDescriptor_direction_tag 3
#define transit_realtime_NyctStopTimeUpdate_scheduled_track_tag 1
#define transit_realtime_NyctStopTimeUpdate_actual_track_tag 2
#define transit_realtime_nyct_feed_header_tag    1001
#define transit_realtime_nyct_trip_descriptor_tag 1001
#define transit_realtime_nyct_stop_time_update_tag 1001

/* Struct field encoding specification for nanopb */
#define transit_realtime_TripReplacementPeriod_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   route_id,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  replacement_period,   2)
#define transit_realtime_TripReplacementPeriod_CALLBACK pb_default_field_callback
#define transit_realtime_TripReplacementPeriod_DEFAULT NULL
#define transit_realtime_TripReplacementPeriod_replacement_period_MSGTYPE transit_realtime_TimeRange

#define transit_realtime_NyctFeedHeader_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   nyct_subway_version,   1) \
X(a, CALLBACK, REPEATED, MESSAGE,  trip_replacement_period,   2)
#define transit_realtime_NyctFeedHeader_CALLBACK pb_default_field_callback
#define transit_realtime_NyctFeedHeader_DEFAULT NULL
#define transit_realtime_NyctFeedHeader_trip_replacement_period_MSGTYPE transit_realtime_TripReplacementPeriod

#define transit_realtime_NyctTripDescriptor_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   train_id,          1) \
X(a, STATIC,   OPTIONAL, BOOL,     is_assigned,       2) \
X(a, STATIC,   OPTIONAL, UENUM,    direction,         3)
#define transit_realtime_NyctTripDescriptor_CALLBACK pb_default_field_callback
#define transit_realtime_NyctTripDescriptor_DEFAULT (const pb_byte_t*)"\x18\x01\x00"

#define transit_realtime_NyctStopTimeUpdate_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   scheduled_track,   1) \
X(a, CALLBACK, OPTIONAL, STRING,   actual_track,      2)
#define transit_realtime_NyctStopTimeUpdate_CALLBACK pb_default_field_callback
#define transit_realtime_NyctStopTimeUpdate_DEFAULT NULL

extern const pb_msgdesc_t transit_realtime_TripReplacementPeriod_msg;
extern const pb_msgdesc_t transit_realtime_NyctFeedHeader_msg;
extern const pb_msgdesc_t transit_realtime_NyctTripDescriptor_msg;
extern const pb_msgdesc_t transit_realtime_NyctStopTimeUpdate_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define transit_realtime_TripReplacementPeriod_fields &transit_realtime_TripReplacementPeriod_msg
#define transit_realtime_NyctFeedHeader_fields &transit_realtime_NyctFeedHeader_msg
#define transit_realtime_NyctTripDescriptor_fields &transit_realtime_NyctTripDescriptor_msg
#define transit_realtime_NyctStopTimeUpdate_fields &transit_realtime_NyctStopTimeUpdate_msg

/* Maximum encoded size of messages (where known) */
/* transit_realtime_TripReplacementPeriod_size depends on runtime parameters */
/* transit_realtime_NyctFeedHeader_size depends on runtime parameters */
/* transit_realtime_NyctTripDescriptor_size depends on runtime parameters */
/* transit_realtime_NyctStopTimeUpdate_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
