[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  nanopb/Nanopb @ 0.4.9
  zinggjm/GxEPD2
  adafruit/Adafruit GFX Library

build_src_filter =
  +<esp32_display/wifi_connection.cpp>
  +<esp32_display/MtaGtfsNanopb/src/**/*.c>

build_flags =
  -Isrc/esp32_display/MtaGtfsNanopb/src
