name=MtaGtfsNanopb
version=0.1.0
author=Laureen
maintainer=Laureen
sentence=Generated GTFS-realtime nanopb files for NYC train time.
paragraph=Includes nanopb runtime decode files and generated MTA GTFS-realtime protobuf bindings.
category=Data Processing
architectures=esp32
includes=MtaGtfsNanopb.h